import type { Metadata } from "next"
import { Inter, Dongle } from "next/font/google"
import "@/app/globals.css"
const inter = Inter({ subsets: ["latin"] })
const dongle = Dongle({ subsets: ["latin"], weight: "300" })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    )
}
